### ISSUE TITLE
Conform to Storage api?

### ISSUE THREAD

**Issue by jasonkarns** [kahnjw/cookie-monster#13]
Cookies are the old-school way to store data client side. local storage and session storage, both conforming to the [Storage API](https://developer.mozilla.org/en-US/docs/Web/API/Storage), are now the recommended way to store client-only data (in general).

Cookies and local/session stores all function fundamentally the same way: as key/value stores. Of course, cookies have additional properties (`path`, `domain`, `secure`, etc), but that's really just metadata on the key/value pair.

I would like to propose that the cookie-monster API conform to the Storage API such that switching between stores is trivial.

As the current API is only `get` and `set`, a first step could be to alias `getItem` to `get` and `setItem` to `set`. Following that, `removeItem` and `clear` methods could be added for safe removal of single items and the entire cookie string, respectively. And finally, for completeness, `key` and `length` could be added (though they are clearly low on the priority list).

I don't see any backwards compatibility issues if `getItem` and `setItem` are aliased to the current methods. Of course, if it's desired to actually deprecate `get`/`set` then it would be beneficial to have them aliased for a while with warning messages, and then remove the `get`/`set` variants in a major version bump.

More than happy to submit a couple PRs if this sounds like something that might be acceptable.

**Comment by kahnjw** [comment]
Yes, I would definitely support this if we keep backward compatibility with the current API.

If we can do this without much work, it might be nice to fork cookie-monster and make the storage backend swappable via a configuration option.

**Comment by kahnjw** [comment]
One could also very easily just use cookie-monster as an installable to do the exact same thing.

**Comment by kahnjw** [comment]
Closed by #15
